// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFLfDpr-km54jWhubUuaarcJlS2IOjUQ',
    appId: '1:51909586532:web:2d5e89354646a4dc013971',
    messagingSenderId: '51909586532',
    projectId: 'sojib-portfolio',
    authDomain: 'sojib-portfolio.firebaseapp.com',
    storageBucket: 'sojib-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_zSIv_h-aLx1lg4hA6xx_SWYZe2LOHgw',
    appId: '1:51909586532:android:0968582a33b60ca4013971',
    messagingSenderId: '51909586532',
    projectId: 'sojib-portfolio',
    storageBucket: 'sojib-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJH3ph9MuuoihyKLMzqQetKFeZ0EVcK8',
    appId: '1:51909586532:ios:99c8717b993d856d013971',
    messagingSenderId: '51909586532',
    projectId: 'sojib-portfolio',
    storageBucket: 'sojib-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );
}
